// Public provider metadata only. Secret values are never represented here.
// Keep this list aligned with the credential service, runtime sidecar, and UI.
export const PROVIDERS = [
  { id: 'finnhub', key: 'FINNHUB_API_KEY', name: 'Finnhub', group: 'Markets', hint: 'Real-time market quotes and company data.' },
  { id: 'alphaVantage', key: 'ALPHA_VANTAGE_API_KEY', name: 'Alpha Vantage', group: 'Markets', hint: 'Market-data fallback and technical indicators.' },
  { id: 'eia', key: 'EIA_API_KEY', name: 'U.S. EIA', group: 'Economy & energy', hint: 'Oil, electricity, inventory, and energy statistics.' },
  { id: 'fred', key: 'FRED_API_KEY', name: 'FRED', group: 'Economy & energy', hint: 'Federal Reserve macroeconomic and shipping indicators.' },
  { id: 'imf', key: 'IMF_API_KEY', name: 'IMF SDMX', group: 'Economy & energy', hint: 'IMF WEO, reserves, and debt datasets.' },
  { id: 'wto', key: 'WTO_API_KEY', name: 'WTO', group: 'Economy & energy', hint: 'Trade policy and trade-flow data.' },
  { id: 'nasaFirms', key: 'NASA_FIRMS_API_KEY', name: 'NASA FIRMS', group: 'Climate & environment', hint: 'Satellite fire detections.' },
  { id: 'openAq', key: 'OPENAQ_API_KEY', name: 'OpenAQ', group: 'Climate & environment', hint: 'Air-quality observations.' },
  { id: 'waqi', key: 'WAQI_API_KEY', name: 'WAQI', group: 'Climate & environment', hint: 'Supplemental Air Quality Index stations.' },
  { id: 'reliefWeb', key: 'RELIEFWEB_APPNAME', name: 'ReliefWeb', group: 'Climate & environment', hint: 'Approved ReliefWeb app name for disaster and climate feeds.', kind: 'text' },
  { id: 'acledToken', key: 'ACLED_ACCESS_TOKEN', name: 'ACLED access token', group: 'Conflict & security', hint: 'Conflict and protest events. Token rotates frequently.' },
  { id: 'acledEmail', key: 'ACLED_EMAIL', name: 'ACLED account email', group: 'Conflict & security', hint: 'Optional automatic ACLED token refresh.', kind: 'email' },
  { id: 'acledPassword', key: 'ACLED_PASSWORD', name: 'ACLED account password', group: 'Conflict & security', hint: 'Optional automatic ACLED token refresh.' },
  { id: 'ucdp', key: 'UCDP_ACCESS_TOKEN', name: 'UCDP', group: 'Conflict & security', hint: 'Uppsala conflict-event access token.' },
  { id: 'cloudflareRadar', key: 'CLOUDFLARE_API_TOKEN', name: 'Cloudflare Radar', group: 'Conflict & security', hint: 'Internet outage and connectivity annotations.' },
  { id: 'urlhaus', key: 'URLHAUS_AUTH_KEY', name: 'URLhaus / ThreatFox', group: 'Cyber intelligence', hint: 'abuse.ch malware and IOC feeds.' },
  { id: 'otx', key: 'OTX_API_KEY', name: 'AlienVault OTX', group: 'Cyber intelligence', hint: 'Optional IOC enrichment.' },
  { id: 'abuseIpdb', key: 'ABUSEIPDB_API_KEY', name: 'AbuseIPDB', group: 'Cyber intelligence', hint: 'IP reputation enrichment.' },
  { id: 'aisStream', key: 'AISSTREAM_API_KEY', name: 'AISStream', group: 'Maritime & aviation', hint: 'Live vessel positions.' },
  { id: 'openSkyClientId', key: 'OPENSKY_CLIENT_ID', name: 'OpenSky client ID', group: 'Maritime & aviation', hint: 'OpenSky OAuth client credential.', kind: 'text' },
  { id: 'openSkyClientSecret', key: 'OPENSKY_CLIENT_SECRET', name: 'OpenSky client secret', group: 'Maritime & aviation', hint: 'OpenSky OAuth client credential.' },
  { id: 'aviationStack', key: 'AVIATIONSTACK_API', name: 'AviationStack', group: 'Maritime & aviation', hint: 'International flight and airport delay data.' },
  { id: 'icao', key: 'ICAO_API_KEY', name: 'ICAO', group: 'Maritime & aviation', hint: 'NOTAM airport closure data.' },
  { id: 'wingbits', key: 'WINGBITS_API_KEY', name: 'Wingbits', group: 'Maritime & aviation', hint: 'Aircraft/operator enrichment.' },
  { id: 'travelpayouts', key: 'TRAVELPAYOUTS_API_TOKEN', name: 'Travelpayouts', group: 'Maritime & aviation', hint: 'Flight-price search (demo feature).' },
  { id: 'samGov', key: 'SAM_GOV_API_KEY', name: 'SAM.gov', group: 'Public procurement', hint: 'United States contracting opportunities.' },
  { id: 'scrapeCreators', key: 'SCRAPECREATORS_API_KEY', name: 'ScrapeCreators', group: 'Social & OSINT', hint: 'Reddit social-velocity source.' },
  { id: 'redditClientId', key: 'REDDIT_CLIENT_ID', name: 'Reddit client ID', group: 'Social & OSINT', hint: 'Legacy OAuth alternative for Reddit.', kind: 'text' },
  { id: 'redditClientSecret', key: 'REDDIT_CLIENT_SECRET', name: 'Reddit client secret', group: 'Social & OSINT', hint: 'Legacy OAuth alternative for Reddit.' },
  { id: 'redditUserAgent', key: 'REDDIT_USER_AGENT', name: 'Reddit user agent', group: 'Social & OSINT', hint: 'Required alongside legacy Reddit OAuth.', kind: 'text' },
  { id: 'telegramApiId', key: 'TELEGRAM_API_ID', name: 'Telegram API ID', group: 'Social & OSINT', hint: 'MTProto application identifier.', kind: 'text' },
  { id: 'telegramApiHash', key: 'TELEGRAM_API_HASH', name: 'Telegram API hash', group: 'Social & OSINT', hint: 'MTProto application credential.' },
  { id: 'telegramSession', key: 'TELEGRAM_SESSION', name: 'Telegram session', group: 'Social & OSINT', hint: 'GramJS session string for curated-channel ingestion.' },
  { id: 'exa', key: 'EXA_API_KEYS', name: 'Exa', group: 'Research & search', hint: 'Targeted news and research search.' },
  { id: 'brave', key: 'BRAVE_API_KEYS', name: 'Brave Search', group: 'Research & search', hint: 'Targeted news and research search fallback.' },
  { id: 'serpApi', key: 'SERPAPI_API_KEYS', name: 'SerpAPI', group: 'Research & search', hint: 'Targeted search fallback.' },
  { id: 'groq', key: 'GROQ_API_KEY', name: 'Groq', group: 'AI enrichment', hint: 'Fast local dashboard summarization fallback.' },
  { id: 'openRouter', key: 'OPENROUTER_API_KEY', name: 'OpenRouter', group: 'AI enrichment', hint: 'Secondary dashboard summarization provider.' },
  { id: 'llmApiUrl', key: 'LLM_API_URL', name: 'OpenAI-compatible LLM URL', group: 'AI enrichment', hint: 'Self-hosted or compatible model endpoint.', kind: 'url' },
  { id: 'llmApiKey', key: 'LLM_API_KEY', name: 'OpenAI-compatible LLM key', group: 'AI enrichment', hint: 'Optional key for the configured LLM endpoint.' },
  { id: 'llmModel', key: 'LLM_MODEL', name: 'LLM model', group: 'AI enrichment', hint: 'Model name used with the compatible endpoint.', kind: 'text' },
];

export const PROVIDER_KEYS = new Set(PROVIDERS.map(({ key }) => key));
export const publicProvider = ({ id, key, name, group, hint, kind = 'password' }) => ({ id, key, name, group, hint, kind });
